name: test_workflow
on:
  push:
    branches: ["main"]
jobs:
  change:
      name: "ServiceNow DevOps Change"
      runs-on: ubuntu-latest
      steps:
        - name: test ServiceNow Change
          id: test_servicenow_change
          uses: ServiceNow/servicenow-devops-change@v6.1.0
          with:
            # Devops Integration Token
            devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
            # ServiceNow Instance URL
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            # Orchestration Tool Id
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            # GitHub Context
            context-github: ${{ toJSON(github) }}
            # Display Name of the Job
            job-name: "test ServiceNow DevOps Change"
            # change-request
            change-request: '{"setCloseCode":"true","attributes":{"short_description":"Public Cloud 운영관리_AP 변경","description":"Public Cloud 운영관리_AP 변경","assignment_group":{"name":"Public Cloud 운영관리_AP"},"implementation_plan":"소프트웨어 업데이트 관련 테스트 이력 및 결과는 테스트 요약 탭에서 확인 할 수 있습니다.; 변경이 승인되면, 예정된 변경 시작 및 종료 시간 사이에 CICD Pipeline이 실행될 것입니다.","backout_plan":"변경 배포에 실패하면, 이전 버전의 소프트웨어가 재배포될 예정입니다.","test_plan":"CICD Pipeline에서 자동화된 테스트 수행, Pipeline 작업 로그를 확인 해주세요."}}'
            deployment-gate: '{"environment":"test-git-environment","jobName":"Deploy"}'

  deploy:
    name: "Deploy"
    environment: test-git-environment
    needs: change
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment scripts
        run: echo 'Deployment step in progress...'

